run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - gofmt
    - gocyclo
    - unconvert
    - dupl
    - goconst
    - gofumpt
    - revive  # replacement for golint

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: testdata/
      linters:
        - all

linters-settings:
  goimports:
    local-prefixes: github.com/MirrexOne/sqlvet
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2