run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - dupl
    - revive

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
    - path: testdata/
      linters:
        - all
    - path: internal/analyzer/analyzer\.go
      linters:
        - gocyclo
      text: "cyclomatic complexity"

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
